name: movielab
description: An open source movie information database application.

publish_to: 'none'
version: 1.0.6+2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  ms_undraw: ^3.0.1+1
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.12
  http: ^0.13.4
  cached_network_image: ^3.2.0
  flutter_rating_bar: ^4.0.0
  google_nav_bar: ^5.0.5
  speech_to_text: ^5.6.0
  page_transition: ^2.0.5
  flutter_slidable: ^1.2.0
  avatar_glow: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.17.12

flutter:
  uses-material-design: true

  assets:
     - assets/logo/logo.png
     - assets/logo/IMDb.png