name: movielab
description: An open source movie information database application.

version: 3.0.1

homepage: https://erfanrht.github.io/MovieLab-Intro
documentation: https://github.com/ErfanRht/MovieLab

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # GetX is used as the state management library for the app.
  get: ^4.6.1

  # Some ui library used in the app.
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  ms_undraw: ^3.0.1+1
  fluttertoast: ^8.0.9
  flutter_spinkit: ^5.1.0
  flutter_rating_bar: ^4.0.0
  google_nav_bar: ^5.0.5
  page_transition: ^2.0.5
  flutter_slidable: ^1.2.0
  avatar_glow: ^2.0.2   
  flashy_tab_bar2: ^0.0.4
  timeline_tile: ^2.0.0

  # Used for saving and loading preferences from the device.
  shared_preferences: ^2.0.12  
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  # Some useful libraries for some parts of the app.
  http: ^0.13.4
  cached_network_image: ^3.2.0
  speech_to_text: ^5.6.0
  url_launcher: ^6.1.4
  fl_chart: ^0.55.0
  share_plus: ^4.0.10
  image_picker: ^0.8.5+3
  flutter_cache_manager: ^3.3.0
  gallery_saver: ^2.3.2
  external_path: ^1.0.1
  permission_handler: ^10.0.0
  file_picker: ^5.0.1


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.17.12
  build_runner: ^2.1.7
  hive_generator: ^1.1.2
  ansicolor: ^2.0.1

flutter:
  uses-material-design: true

  assets:
     - assets/images/logos/
     - assets/images/